<a href="https://colab.research.google.com/github/batchuraja484/NLP_Techniques_ML_DL/blob/master/HuggingFace_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install transformers

     |████████████████████████████████| 1.3MB 10.6MB/s 
     |████████████████████████████████| 890kB 45.0MB/s 
     |████████████████████████████████| 2.9MB 46.0MB/s 
     |████████████████████████████████| 1.1MB 49.9MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893257 sha256=fa25f8b2b75841530e274be74847ed2b51f66f1860a21fbc205af4eae4b17dd9
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [4]:
from transformers import pipeline

Sentiment Analysis

In [5]:
nlp_sentiment=pipeline("sentiment-analysis")

In [6]:
sen_result=nlp_sentiment("Develop cutting edge text mining, text analytics and NLP machine learning algorithms and NLP technique. It's especially designed to extract key information from textual data related to specialty chemical industries")

In [7]:
sen_result[0]

{'label': 'POSITIVE', 'score': 0.9967056512832642}

Question and Answer System

In [8]:
nlp_qa=pipeline("question-answering")

In [17]:
qa_data={'context':'My Name is Raja and I am working as data scientinst and Raja salary is 60k',
         'question':'what is Raja Salary'}

In [18]:
qa_result=nlp_qa(qa_data)
qa_result

/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils_base.py:1423: FutureWarning: The `max_len` attribute has been deprecated and will be removed in a future version, use `model_max_length` instead.
  FutureWarning,


{'answer': 'My Name is Raja and I am working as data scientinst',
 'end': 51,
 'score': 0.2644665837287903,
 'start': 0}

Predicting masks

In [19]:
nlp_mask=pipeline("fill-mask")

Some weights of RobertaForMaskedLM were not initialized from the model checkpoint at distilroberta-base and are newly initialized: ['lm_head.decoder.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [21]:
mask_result=nlp_mask('I hope you <mask> the work')
mask_result

[{'score': 0.7173811197280884,
  'sequence': '<s>I hope you enjoyed the work</s>',
  'token': 3776,
  'token_str': 'Ġenjoyed'},
 {'score': 0.2346116304397583,
  'sequence': '<s>I hope you enjoy the work</s>',
  'token': 2254,
  'token_str': 'Ġenjoy'},
 {'score': 0.02108212746679783,
  'sequence': '<s>I hope you liked the work</s>',
  'token': 6640,
  'token_str': 'Ġliked'},
 {'score': 0.01576649211347103,
  'sequence': '<s>I hope you appreciate the work</s>',
  'token': 5478,
  'token_str': 'Ġappreciate'},
 {'score': 0.0034931532572954893,
  'sequence': '<s>I hope you appreciated the work</s>',
  'token': 10874,
  'token_str': 'Ġappreciated'}]

NER system

In [22]:
nlp_ner=pipeline("ner")

In [23]:
ner_result=nlp_ner('I am Rajendra Kumar Batchu and I am working in Tech Mahindra Singapore')
ner_result

[{'entity': 'I-PER', 'index': 3, 'score': 0.9994914531707764, 'word': 'Raj'},
 {'entity': 'I-PER',
  'index': 4,
  'score': 0.9995704889297485,
  'word': '##endra'},
 {'entity': 'I-PER', 'index': 5, 'score': 0.9995444416999817, 'word': 'Kumar'},
 {'entity': 'I-PER', 'index': 6, 'score': 0.9996671080589294, 'word': 'Bat'},
 {'entity': 'I-PER', 'index': 7, 'score': 0.9849494099617004, 'word': '##chu'},
 {'entity': 'I-ORG', 'index': 13, 'score': 0.9981523156166077, 'word': 'Tech'},
 {'entity': 'I-ORG', 'index': 14, 'score': 0.9989343285560608, 'word': 'Ma'},
 {'entity': 'I-ORG',
  'index': 15,
  'score': 0.9906812310218811,
  'word': '##hin'},
 {'entity': 'I-ORG',
  'index': 16,
  'score': 0.9931785464286804,
  'word': '##dra'},
 {'entity': 'I-ORG',
  'index': 17,
  'score': 0.9600574970245361,
  'word': 'Singapore'}]

Text Generation

In [6]:
import torch
from transformers import GPT2Tokenizer,GPT2LMHeadModel,BertTokenizer,BertLMHeadModel

In [7]:
gpt_tokenizer=GPT2Tokenizer.from_pretrained('gpt2')
gpt_model=GPT2LMHeadModel.from_pretrained('gpt2')

In [8]:
gpt_tokenizer('Hi Raja')

{'input_ids': [17250, 13308, 64], 'attention_mask': [1, 1, 1]}

In [9]:
gpt_tokenizer('let us see how this turns')

{'input_ids': [1616, 514, 766, 703, 428, 4962], 'attention_mask': [1, 1, 1, 1, 1, 1]}

In [2]:
!nvidia-smi

Thu Nov 12 04:27:39 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8     9W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [11]:
inp_text="let us see how this turns"
indexed_tokens=gpt_tokenizer.encode(inp_text)
token_tensor=torch.tensor([indexed_tokens])
print(token_tensor)
gpt_model.eval()
token_tensor_cuda=token_tensor.to('cuda')
print(token_tensor_cuda)
gpt_model.to('cuda')

tensor([[1616,  514,  766,  703,  428, 4962]])
tensor([[1616,  514,  766,  703,  428, 4962]], device='cuda:0')


GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0): Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (1): Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): Laye

Single Word Predictions

In [17]:
with torch.no_grad():
  sing_outputs=gpt_model(token_tensor_cuda)
  single_prediction=sing_outputs[0]
print(sing_outputs[0].shape)
print(single_prediction)
predicted_index=torch.argmax(single_prediction[0,-1,:]).item()
predicted_text=gpt_tokenizer.decode(indexed_tokens+[predicted_index])
print(predicted_text)


torch.Size([1, 6, 50257])
tensor([[[ -30.7175,  -30.1622,  -33.3332,  ...,  -38.5832,  -38.0198,
           -30.9952],
         [ -98.4159, -100.4491, -105.3793,  ..., -107.8816, -107.9807,
          -101.7302],
         [-103.1150, -104.9184, -110.8609,  ..., -113.1474, -114.1165,
          -107.9634],
         [ -99.5847, -101.0270, -107.6020,  ..., -106.5477, -108.5505,
          -102.5721],
         [ -94.9962,  -94.9470, -100.2781,  ...,  -99.5511,  -99.7550,
           -96.2084],
         [ -82.4671,  -84.7634,  -89.7857,  ...,  -90.9548,  -94.7276,
           -85.1815]]], device='cuda:0')
let us see how this turns out


Working for multiple sentences

Summerizing the Text

In [35]:
#full_text="Shakespeare occupies a position unique in world literature. Other poets, such as Homer and Dante, and novelists, such as Leo Tolstoy and Charles Dickens, have transcended national barriers, but no writer’s living reputation can compare to that of Shakespeare, whose plays, written in the late 16th and early 17th centuries for a small repertory theatre, are now performed and read more often and in more countries than ever before. The prophecy of his great contemporary, the poet and dramatist Ben Jonson, that Shakespeare “was not of an age, but for all time,” has been fulfilled. It may be audacious even to attempt a definition of his greatness, but it is not so difficult to describe the gifts that enabled him to create imaginative visions of pathos and mirth that, whether read or witnessed in the theatre, fill the mind and linger there. He is a writer of great intellectual rapidity, perceptiveness, and poetic power. Other writers have had these qualities, but with Shakespeare the keenness of mind was applied not to abstruse or remote subjects but to human beings and their complete range of emotions and conflicts. Other writers have applied their keenness of mind in this way, but Shakespeare is astonishingly clever with words and images, so that his mental energy, when applied to intelligible human situations, finds full and memorable expression, convincing and imaginatively stimulating. As if this were not enough, the art form into which his creative energies went was not remote and bookish but involved the vivid stage impersonation of human beings, commanding sympathy and inviting vicarious participation. Thus, Shakespeare’s merits can survive translation into other languages and into cultures remote from that of Elizabethan England."
full_text="Vijayawada, also known as Bezawada is a city in the Indian state of Andhra Pradesh.It lies on the banks of River Krishna surrounded by the hills of Eastern Ghats known as Indrakeeladri Hills in Krishna District. It geographically lies on the center spot of Andhra Pradesh.The city has been described as the commercial, political, educational and media capital of Andhra Pradesh,second largest city in Andhra Pradesh and is one of the rapidly growing urban areas in India.Vijayawada is considered to be a sacred place for residing one of the most visited and famous temples of Andhra Pradesh and India,Kanka Durga Temple of Hindu Goddess Durga.It also serves as the ritual host of Pushkaram (a river worshipping ritual in Andhra Pradesh and India) of River Krishna.There is a legend which says that Arjuna, one of the heroes of the Indian epic Mahabharata, prayed on top of the Indrakeeladri Hill in the city and won the blessings of Lord Shiva to get the Pashupatastra to win the Kurukshetra War.It was called Vijayavatika (meaning Land of Victory in Telugu) when Goddess Durga killed the demon Mahishasura and rested on the Indrakeeladri Hill by the River Krishna establishing the victory over evil hence the place got its name Vijayavatika, Vijaya- meaning victory and Vatika meaning Place or land in Telugu.Over the years Vijayavatika name changed to Rajendra Chola Pura during Chola Dynasty and Bezawada during British rule and eventually to Vijayawada"

In [25]:
!git clone https://github.com/huggingface/pytorch-transformers.git

Cloning into 'pytorch-transformers'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 50842 (delta 3), reused 9 (delta 0), pack-reused 50830
Receiving objects: 100% (50842/50842), 37.40 MiB | 29.28 MiB/s, done.
Resolving deltas: 100% (35515/35515), done.


In [26]:
!python pytorch-transformers/examples/text-generation/run_generation.py \
    --model_type=gpt2 \
    --length=100 \
    --model_name_or_path=gpt2 \

Traceback (most recent call last):
  File "pytorch-transformers/examples/text-generation/run_generation.py", line 295, in <module>
    main()
  File "pytorch-transformers/examples/text-generation/run_generation.py", line 230, in main
    prompt_text = args.prompt if args.prompt else input("Model prompt >>> ")
KeyboardInterrupt
^C


In [27]:
from transformers import BartTokenizer,BartForConditionalGeneration,BartConfig
mart_model=BartForConditionalGeneration.from_pretrained('facebook/bart-large-cnn')
bart_tokenizer=BartTokenizer.from_pretrained('facebook/bart-large-cnn')

In [36]:
inputs=bart_tokenizer.batch_encode_plus([full_text],max_length=1024,return_tensors='pt')
summary_ids=mart_model.generate(inputs['input_ids'],num_beams=4,max_length=100,early_stopping=False)
for ids in summary_ids:
  Summary_test=bart_tokenizer.decode(ids,skip_special_tokens=True,clean_up_tokenization_spaces=False)
  print(len(full_text),len(Summary_test))
  print(Summary_test)



1456 406
Vijayawada, also known as Bezawada is a city in the Indian state of Andhra Pradesh. It lies on the banks of River Krishna surrounded by the hills of Eastern Ghats known as Indrakeeladri Hills in Krishna District. The city is considered to be a sacred place for residing one of the most visited and famous temples, Kanka Durga Temple of Hindu Goddess Durga. It also serves as the ritual host of Pushkaram (a
